
<html><head><title>简历预览</title><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta name="robots" content="nofollow" /><link rel="stylesheet" type="text/css" href="https://img00.zhaopin.cn/2012/css/reset.min.css" media="all" /><link rel="stylesheet" type="text/css" href="https://i.zhaopin.com/Content/css/resume_preview.css" media="all" /></head><body><div class="resumeBody"><div style="height:32px;padding-left:20px;color:#fd7222;font-size:14px;"><p style="float:left;line-height:28px">使用简历置顶服务，简历被查看次数至少可提高<span style="font-size:16px">50</span>
            次！
        </p><a target="_blank" class="setTopBtn" style="display: block;float:right;width:114px;height:28px;line-height:28px;border-radius: 14px;background: #fdb12a;color: #fff;font-size: 12px;text-align: center;" href="http://i.zhaopin.com/Order/OrderManager/UnPay?pointId=&serviceId=&extid=JM345573646R90250000000&VersionNum=1&resumeName=&joinpoint=Preview">置顶简历</a></div><div class="summary"><img width="70" height="90" align="right" class="headerImg" alt="董妍" src="https://mypics.zhaopin.cn/avatar/2018/3/21/7f02cf80-a77e-43b3-b08a-38621cc4bb7d.jpg" /><h1>董妍</h1>女<span class="ver-line">|</span>未婚<span class="ver-line">|</span>1992年2月生<span class="ver-line">|</span>
        户口：吉林-长春<span class="ver-line">|</span>
        现居住于:上海<br />3年工作经验
        <span class="ver-line">|</span>群众<p>15000551923</p><p>
            E-mail：<a href="mailto:diane3****@163.com">diane34020@163.com</a></p></div><dl class="details"><dt><h5>求职意向</h5></dt><dd><ul><li><strong>工作性质：</strong>全职</li><li><strong>期望职业：</strong>PHP开发工程师、</li><li><strong>期望行业：</strong>计算机软件</li><li><strong>工作地区：</strong>上海</li><li><strong>期望月薪：</strong>10001-15000元/月</li><li><strong>目前状况：</strong>我对现有工作还算满意，如有更好的工作机会，我也可以考虑。（到岗时间另议）</li></ul></dd><dt><h5>自我评价</h5></dt><dd><p style="width:574px; overflow:hidden;word-break: break-all; word-wrap:break-word;">踏实稳重、能吃苦耐劳，对人友善，服从安排，善于学习，乐于思考。</p></dd><dt><h5>工作经历</h5></dt><dd><div class="work-experience"><p>2017/05 --
                    至今
                </p><h6>阅文集团<span class="ver-line">|</span>php开发工程师</h6><p><span>
                          行业类别： 互联网/电子商务</span><span><span class="ver-line">|</span>企业性质：上市公司</span><span><span class="ver-line">|</span>规模：500-999人</span><span><span class="ver-line">|</span>职位月薪：10001-15000元/月</span></p><p><strong>工作描述：</strong><br />在阅文集团我的工作职责是负责运营平台的活动开发，主要是app端的运营活动，引导用户充值消费，购买书籍、签到等。</p></div><div class="work-experience"><p>2016/05 -- 2017/05</p><h6>上海信隆行信息科技股份有限公司<span class="ver-line">|</span>php程序员</h6><p><span>
                          行业类别： 互联网/电子商务</span><span><span class="ver-line">|</span>企业性质：合资</span><span><span class="ver-line">|</span>规模：20-99人</span><span><span class="ver-line">|</span>职位月薪：10001-15000元/月</span></p><p><strong>工作描述：</strong><br />在信隆行我的工作主要是负责网站运营后台开发，与产品、运营、测试进行对接，满足客户及公司内部人员的后台需求，关注后台功能运行情况，对运营后台功能进行迭代与维护。<br/>开发环境：OS系统、CI框架、MYSQL数据库、Apache服务器、Redis缓存、git版本控制系统<br/>公司网站：www.easyrong.com</p></div><div class="work-experience"><p>2015/03 -- 2016/05</p><h6>上海若信信息技术有限公司<span class="ver-line">|</span>PHP工程师</h6><p><span>
                          行业类别： 计算机软件</span><span><span class="ver-line">|</span>企业性质：外商独资</span><span><span class="ver-line">|</span>规模：20-99人</span><span><span class="ver-line">|</span>职位月薪：8001-10000元/月</span></p><p><strong>工作描述：</strong><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;曾经在上海若信信息技术有限公司的技术部作为一名PHP工程师，公司的网站是www.wealink.com 即若邻网招聘网站，我在公司主要工作是网站功能实现，参与过的项目有吐槽专题的投票功能、求职送红酒等。参与公司网站的重大项目重构工作，主要负责网站的后台开发，和前端部分功能的开发。目前负责维护公司的网站，实现新的需求以及修复线上bug。通过这一年多的工作，让我对我的基础知识掌握的更加牢固，同时也学到了很多工作中常用到的技术，对php语言有了更深入的了解。（工作开发环境：phpstorm编辑器、phalcon框架、git版本管理、redis缓存、linux操作系统、supervisor 守护进程、jsonRpc、elasticsearch搜索引擎）<br/>公司网站：www.wealink.com</p></div></dd><dt><h5>项目经验</h5></dt><dd><div class="project-experience"><p>2016/05 -- 2017/05</p><h6>信隆行运营后台开发</h6><div><p><strong>软件环境：</strong>windows操作系统</p><p><strong>开发工具：</strong>ci框架、redis缓存、mysql数据库、restAPI、git远程版本控制、jenkins、nginx服务器</p></div><p><strong>责任描述：</strong><br />负责信隆行后台投融资的管理，协助运营、产品、市场人员对即将展开的活动及时进行推广和管理、及时满足运营人员的市场需求，对现有的公司客户进行管理和维护。<br/></p><p><strong>项目简介：</strong><br /></p></div><div class="project-experience"><p>2015/06 -- 2015/09</p><h6>若邻网重构项目</h6><div><p><strong>软件环境：</strong>Ubuntu操作系统</p><p><strong>开发工具：</strong>phalcon框架、redis缓存、supervisorctl守护进程、elasticsearch搜索引擎、jsonRpc、mysql数据库、git远程控制、virtualbox虚拟机、Ubuntu操作系统等</p></div><p><strong>责任描述：</strong><br />在若邻网项目重构中，我全程参与项目各个模块的需求讨论、设计数据库、绘制数据结构图、参与开发前台和后台的功能。主要有职位发布与删除修改模块、套餐模块、后台管理模块等。</p><p><strong>项目简介：</strong><br />若邻网之所以重构是为了在求职者和招聘方之间构架一个沟通的桥梁，方便求职者随时掌握简历的投递进度。方便招聘方随时处理求职者的简历信息。</p></div></dd><dt><h5>教育经历</h5></dt><dd><div class="education-background"><p>2011/09 -- 2015/06</p><h6>上海立信会计学院<span class="ver-line">|</span>信息科学技术<span class="ver-line">|</span>本科<span class="ver-line">|</span>统招</h6></div></dd><dt><h5>在校学习情况</h5></dt><dd><div><h6>
                    曾获 院校级 三等奖 奖学金
                </h6></div></dd><dd><div><h6>
                    曾获 院校级 三等奖 奖学金
                </h6></div></dd><dd><p>我曾是院组织部成员，参与组织过学院的老乡会等活动，也积极参加过学校的各种社会实践活动，获得文体积极分子称号。</p></dd><dd><div><h6>2012/10 文体积极分子 院校级</h6><p>因积极参加学校运动会的开幕式啦啦队获此殊荣</p></div></dd><dd><div><h6>2013/07 优秀团员 院校级</h6><p>因学习优秀、与同学关系融洽获此殊荣</p></div></dd><dt><h5>在校实践经验</h5></dt><dd><div class="social"><p>2012/02 -- 2012/02</p><h6>走进社区关爱孤寡老人</h6><p>参加了班级组织的走进社区关爱老人的活动，进入社区，为孤寡老人打扫卫生、和他们聊天 </p></div></dd><dt><h5>培训经历</h5></dt><dd><div class="training"><p>2014/06 -- 2014/11</p><h6>上海达内软件培训中心</h6><p><div><strong>培训课程：</strong>PHP网站开发<br /></div><div><strong>所获证书：</strong>php软件开发工程师高级、高级程序员、互联网工程师高级<br /></div><div><strong>培训地点：</strong>上海凯旋中心<br /></div><div><strong>培训描述：</strong>我在达内学习了5个月的php网站开发，熟练掌握了LAMP结构、以及HTML、XML、JS、CSS、jQuery、Ajax、Yii框架和ThinkPHP框架、MVC框架、DedeCMS二次开发系统。熟练掌握前后台技术，以及MySQL数据库和Apache服务器，对php编程有一定深入的了解。</div></p></div><div class="training"><p>2014/06 -- 2014/12</p><h6>上海先知教育</h6><p><div><strong>培训课程：</strong>广告设计师高级<br /></div><div><strong>所获证书：</strong>广告设计师高级<br /></div><div><strong>培训地点：</strong>上海立信会计学院<br /></div><div><strong>培训描述：</strong>在校期间，我参加了学校组织的为期3个月的广告设计师高级的培训， 学习了广告设计的基础，包括PhotoShop、Flash、3DMax、绘图等，通过考试，取得了广告设计师高级证书。</div></p></div></dd><dt><h5>证书</h5></dt><dd><div class="certificates"><p>2014/11</p><h6>高级程序员</h6><p /></div></dd><dd><div class="certificates"><p>2015/03</p><h6>广告设计师高级</h6><p /></div></dd><dd><div class="certificates"><p>2013/04</p><h6>普通话等级证书</h6><p /></div></dd><dd><div class="certificates"><p>2013/04</p><h6>大学英语六级</h6><p /></div></dd><dt><h5>语言能力</h5></dt><dd><div class="language-skill">英语<span>
                            ：读写能力熟练<span class="ver-line">|</span> 听说能力熟练</span></div></dd><dt><h5>专业技能</h5></dt><dd><div class="professional-skill">PHP网站开发<span class="ver-line">|</span>熟练<span class="ver-line">|</span>24</div></dd><dt><h5>特长职业目标</h5></dt><dd><p>希望在PHP技术方面更进一步的同时，也扩展一下其他的编程语言。多掌握几门技术、争取做到全栈。</p></dd><dt><h5>兴趣爱好</h5></dt><dd><p>喜欢打打羽毛球和爬山，看电影、唱歌、旅游等放松心情的活动</p></dd></dl><input id="neturlparam" type="hidden" value="AppId=1&Id=634557364&Timestamp=1521637507&Callback=&signature=E3D205DD9DE62BDED3F73440243D1665" /></div></body></html>